fix(deploy): move '$leading_path' variable definition in eck-operator helm chart (#8075)
This fixes an error that is thrown by Helm when templating the `eck-operator` chart. In this case, consider the following variables file:

```bash
config:
  metrics:
    port: "6000"
    secureMode:
      enabled: true
      tls:
        certificateSecret: "my-metrics-cert-secret"
        caSecret: "my-metrics-cert-secret"
        insecureSkipVerify: false
```

Running `helm template` with the above values generates the following error:

```bash
Error: template: eck-operator/templates/serviceMonitor.yaml:25:49: executing "eck-operator/templates/serviceMonitor.yaml" at <.Values.config.metrics.secureMode.tls.caMountDirectory>: can't evaluate field Values in type string

Use --debug flag to render out invalid YAML
```

This error occurs because when modifying the scope using `with`, the reference for `.Values`, for example, is lost ([helm docs](https://helm.sh/docs/chart_template_guide/control_structures/#modifying-scope-using-with)).