Small UX improvement during Fleet setup (#8350)
This tries to address some long-standing UX issues with the Fleet setup in ECK: 

* clearer error messages 
* distinguish transient errors (e.g. user creation) from actual misconfigurations
* provide more context from HTTP error responses to narrow down the root cause in case of actual user error

Transient error (401) during user creation is communicated as such in the event

```
26m Warning Delayed agent/fleet-server ECK cannot setup Fleet enrollment. Waiting for Kibana credentials. This should be a transient issue.
```

In addition adds a debug log statment in the operator logs. The intent here is to allow debugging persistent 401 errors that are not related to propagation delays in k8s secrets and ES hot-reloading the credentials: 

```
2024-12-19T12:37:15.924+0100	DEBUG	agent-controller	failed to request https://kibana-kb-http.default.svc:5601/api/fleet/setup, status is 401, [security_exception
	Root causes:
		security_exception: unable to authenticate user [default-elastic-agent-agent-kb-user] for REST request [/_security/_authenticate]]: unable to authenticate user [default-elastic-agent-agent-kb-user] for REST request [/_security/_authenticate]	{"service.version": "2.17.0-SNAPSHOT+fc606c33", "iteration": "225", "namespace": "default", "agent_name": "elastic-agent"}
```

Persistent 404 error (here incorrect policyID)  with additional context in the k8s event and log statement 

```
16m Warning Unexpected agent/fleet-server ECK cannot setup Fleet enrollment. This is likely a mis-configuration. failed to request https://kibana-kb-http.default.svc:5601/api/fleet/enrollment_api_keys, status is 404, Agent policy "eck-fleet-server-policy" not found
```